FROM golang:1.20 as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -v -o backend ./cmd/backend/main.go

FROM alpine:3.18

COPY --from=builder /app/backend /backend

CMD ["/backend"]
