version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      - mynetwork
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - redis
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
      - mynetwork
    depends_on:
      - app
  redis:
    image: "redis:7.2-alpine"
    networks:
      - mynetwork
    ports:
      - "6379:6379"
networks:
  mynetwork:
    driver: bridge